default: &default
  adapter: postgresql
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: vct_development

test:
  <<: *default
  database: vct_test
